version: '3.8'

services:
  regular-tasks:
    image: ghcr.io/jvsoest/regular_tasks:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./jobs_config.json:/app/jobs_config.json
      # Mount module directories (add as needed)
      - ./email_move:/app/email_move
    environment:
      - FLASK_ENV=production
      - TZ=UTC
      # Log rotation settings (optional)
      - LOG_ROTATION_ENABLED=true
      - LOG_ROTATION_DAYS=7
      - LOG_ROTATION_COUNT=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - regular-tasks
  #   restart: unless-stopped
